"use strict";

// Maps from game identifier to JS KeyEvent identifier
const InputMapping =
{
    "A": "KeyA",
    "B": "KeyB",
    "C": "KeyC",
    "D": "KeyD",
    "E": "KeyE",
    "F": "KeyF",
    "G": "KeyG",
    "H": "KeyH",
    "I": "KeyI",
    "J": "KeyJ",
    "K": "KeyK",
    "L": "KeyL",
    "M": "KeyM",
    "N": "KeyN",
    "O": "KeyO",
    "P": "KeyP",
    "Q": "KeyQ",
    "R": "KeyR",
    "S": "KeyS",
    "T": "KeyT",
    "U": "KeyU",
    "V": "KeyV",
    "W": "KeyW",
    "X": "KeyX",
    "Y": "KeyY",
    "Z": "KeyZ",
    "1" : "Digit1",
    "2" : "Digit2",
    "3" : "Digit3",
    "4" : "Digit4",
    "5" : "Digit5",
    "6" : "Digit6",
    "7" : "Digit7",
    "8" : "Digit8",
    "9" : "Digit9",
    "0" : "Digit0",
    "Enter": "Enter",
    "Tab": "Tab",
};

export default InputMapping;
